vars:
  version: ???
  resolution: 224
  minaug_min_scale: 0.2
  byolaug_min_scale: 0.08

kind: imagenet
version: ${vars.version}
split: train
sample_wrappers:
  - kind: kd_multi_view_wrapper
    configs:
      - n_views: 2
        transform:
          - kind: kd_random_resized_crop
            size: ${vars.resolution}
            scale:
              - ${vars.minaug_min_scale}
              - 1.0
            interpolation: bicubic
          - kind: kd_random_horizontal_flip
          - kind: kd_image_net_norm
      - n_views: 1
        transform:
          - kind: kd_random_resized_crop
            size: ${vars.resolution}
            scale:
              - ${vars.byolaug_min_scale}
              - 1.0
            interpolation: bicubic
          - kind: kd_random_horizontal_flip
          - kind: kd_random_color_jitter
            p: 0.8
            brightness: 0.4
            contrast: 0.4
            saturation: 0.2
            hue: 0.1
          - kind: kd_gaussian_blur_pil
            sigma:
              - 0.1
              - 2.0
          - kind: kd_random_grayscale
            p: 0.2
          - kind: kd_image_net_norm
      - n_views: 1
        transform:
          - kind: kd_random_resized_crop
            size: ${vars.resolution}
            scale:
              - ${vars.byolaug_min_scale}
              - 1.0
            interpolation: bicubic
          - kind: kd_random_horizontal_flip
          - kind: kd_random_color_jitter
            p: 0.8
            brightness: 0.4
            contrast: 0.4
            saturation: 0.2
            hue: 0.1
          - kind: kd_random_gaussian_blur_pil
            p: 0.1
            sigma:
              - 0.1
              - 2.0
          - kind: kd_random_grayscale
            p: 0.2
          - kind: kd_random_solarize
            p: 0.2
            threshold: 128
          - kind: kd_image_net_norm
