wandb: v4
stage_name: ade20k-probe
name: ibot-l16--res224-e50-dinogrid-lo3
processors:
  - kind: probe_processor
    probe_kind: semseg_probe
    grid: dinov2-semseg-reduced
    every_nth_block: 4

datasets:
  train:
    template: ${yaml:datasets/ade20k/train_minaug}
    template.vars.resolution: 224
  test:
    template: ${yaml:datasets/ade20k/test_slide}

model:
  kind: probe_model
  norm_mode: batchnorm
  encoder:
#    kind: vit.vit
#    patch_size: 16
#    kwargs: ${select:large:${yaml:models/vit}}
    initializers:
      - kind: pretrained_initializer
        weights_file: ibot_large16_rand.pth
        use_checkpoint_kwargs: true
  heads: from_processor

trainer:
  kind: semseg_trainer
  precision: bfloat16
  backup_precision: float16
  max_epochs: 50
  effective_batch_size: 16
  log_every_n_epochs: 1
  callbacks:
    - kind: offline_segmentation_callback
      every_n_epochs: 10
      batch_size: 1
      dataset_key: test
      ignore_index: -1
      mode: slide
      mode_kwargs:
        stride: [ 170, 170 ]

