kind: cifar100
split: train
sample_wrappers:
  - kind: x_transform_wrapper
    transform:
      - kind: kd_random_resized_crop
        size: 224
        scale:
          - 0.08
          - 1.0
        interpolation: bicubic
      - kind: kd_random_horizontal_flip
      - kind: kd_imagenet_norm