wandb: v4
stage_name: stage2
name: h14-d2v2
processors:
  - kind: stage2_processor
vars:
  max_epochs: 20
  batch_size: 512
  optim:
    kind: adamw
    lr: 2.0e-4
    betas: [ 0.9, 0.95 ]
    weight_decay: 1.0e-5
    schedule:
      template: ${yaml:schedules/wupcos_epoch}
      template.vars.end_epoch: 4

datasets:
  train:
    template: ${yaml:datasets/imagenet/train_byolaug_localviews}
    template.vars.version: imagenet1k
    template.vars.local_resolution: 98
  train_noaug_10p:
    template: ${yaml:datasets/imagenet/train_noaug}
    template.vars.version: imagenet1k_10percent_simclrv2
  test:
    template: ${yaml:datasets/imagenet/test_noaug}
    template.vars.version: imagenet1k

model:
  kind: contrastive_model
  encoder:
#    kind: vit.vit
#    patch_size: 16
#    kwargs: ${select:base:${yaml:models/vit}}
    is_frozen: true
    initializers:
      - kind: pretrained_initializer
        weights_file: data2vec2_huge14.pt
        use_checkpoint_kwargs: true
  heads:
    # nnclr
    nnclr_temp03_cls:
      kwargs: ${select:base:${yaml:models/nnclr}}
      optim: ${vars.optim}
    nnclr_temp03_cls31:
      kwargs: ${select:base:${yaml:models/nnclr}}
      optim: ${vars.optim}
    nnclr_temp03_cls30:
      kwargs: ${select:base:${yaml:models/nnclr}}
      optim: ${vars.optim}
    nnclr_temp03_cls29:
      kwargs: ${select:base:${yaml:models/nnclr}}
      optim: ${vars.optim}
    nnclr_temp03_cls28:
      kwargs: ${select:base:${yaml:models/nnclr}}
      optim: ${vars.optim}
    nnclr_temp03_cls27:
      kwargs: ${select:base:${yaml:models/nnclr}}
      optim: ${vars.optim}
    nnclr_temp03_cls26:
      kwargs: ${select:base:${yaml:models/nnclr}}
      optim: ${vars.optim}
    nnclr_temp03_cls25:
      kwargs: ${select:base:${yaml:models/nnclr}}
      optim: ${vars.optim}
    nnclr_temp03_cls24:
      kwargs: ${select:base:${yaml:models/nnclr}}
      optim: ${vars.optim}
    nnclr_temp03_cls23:
      kwargs: ${select:base:${yaml:models/nnclr}}
      optim: ${vars.optim}
    nnclr_temp03_cls22:
      kwargs: ${select:base:${yaml:models/nnclr}}
      optim: ${vars.optim}
    nnclr_temp03_cls21:
      kwargs: ${select:base:${yaml:models/nnclr}}
      optim: ${vars.optim}
    nnclr_temp03_cls20:
      kwargs: ${select:base:${yaml:models/nnclr}}
      optim: ${vars.optim}

trainer:
  kind: contrastive_trainer
  precision: bfloat16
  backup_precision: float16
  max_epochs: ${vars.max_epochs}
  effective_batch_size: ${vars.batch_size}
  log_every_n_epochs: 1
  callbacks:
    - kind: checkpoint_callback
    - kind: checkpoint_callback
      every_n_epochs: 1
      save_weights: false
      save_optim: false
      save_latest_weights: true
      save_latest_optim: true
    # k-NN 10%
    - kind: offline_knn_metrics_callback
      every_n_epochs: 1
      train_dataset_key: train_noaug_10p
      test_dataset_key: test
      extractors: from_processor