wandb: v4
name: 7mzhpufg--vpt
stage_name: 10p
vars:
  stage_id: 7mzhpufg
  pooling: class_token

datasets:
  train:
    template: ${yaml:datasets/imagenet/train_minaug_smooth}
    template.vars.version: imagenet1k_10percent_simclrv2
  test:
    template: ${yaml:datasets/imagenet/test_noaug}
    template.vars.version: imagenet1k

model:
#  patch_size: 16
#  kwargs: ${select:large:${yaml:models/vit}}
  kind: vit.vit_vpt
  num_prompt_tokens: 8
  prompt_token_dim: 192
  mode: classifier
  pooling:
    kind: ${vars.pooling}
  freezers:
    - kind: vit_block_freezer
      end_percent: 1.0
      freeze_last_norm: true
  optim:
    kind: adamw
    lr: 1.0e-3
    betas: [ 0.9, 0.999 ]
    weight_decay: 0.0
    schedule:
      - schedule:
          kind: linear_increasing_schedule
          exclude_first: true
          exclude_last: true
        end_epoch: 5
      - schedule:
          kind: cosine_decreasing_schedule
          exclude_last: true
  initializers:
    - kind: previous_run_initializer
      stage_id: ${vars.stage_id}
      stage_name: stage3
      model_name: contrastive_model.encoder
      model_info: ema=0.9999
      checkpoint: last
      use_checkpoint_kwargs: true

trainer:
  kind: classification_trainer
  precision: bfloat16
  max_epochs: 50
  effective_batch_size: 128
  log_every_n_epochs: 1
  callbacks:
    - kind: checkpoint_callback
    - kind: offline_accuracy_callback
      every_n_epochs: 1
      dataset_key: test
    - kind: best_checkpoint_callback
      every_n_epochs: 1
      metric_key: accuracy1/test/main