vars:
  resolution: ??

kind: ade20k
split: train
sample_wrappers:
  - kind: semseg_transform_wrapper
    transforms:
      - kind: kd_semseg_random_resize
        base_size:
        - ${vars.resolution}
        - ${eval:${vars.resolution} * 2}
        ratio: [ 0.5, 2.0 ]
        interpolation: bicubic
      - kind: kd_semseg_random_crop
        size: ${vars.resolution}
        max_category_ratio: 0.75
      - kind: kd_semseg_random_horizontal_flip
      - kind: kd_image_net_norm
      - kind: kd_semseg_pad
        size: ${vars.resolution}
