vars:
  version: ???
  resolution: 224
  min_scale: 0.08

kind: inat
version: ${vars.version}
split: train
sample_wrappers:
  - kind: x_transform_wrapper
    transform:
      - kind: kd_random_resized_crop
        size: ${vars.resolution}
        scale:
          - 0.08
          - 1.0
        interpolation: bicubic
      - kind: kd_random_horizontal_flip
      - kind: kd_rand_augment
        num_ops: 2
        magnitude: 9
        magnitude_std: 0.5
        interpolation: bicubic
        fill_color: [ 124, 116, 104 ]
      - kind: kd_image_net_norm
      - kind: kd_random_erasing
        p: 0.25
        mode: pixelwise
        max_count: 1
  - kind: label_smoothing_wrapper
    smoothing: 0.1
collators:
  - kind: kd_mix_collator
    mixup_alpha: 0.8
    cutmix_alpha: 1.0
    mixup_p: 0.5
    cutmix_p: 0.5
    apply_mode: batch
    lamb_mode: batch
    shuffle_mode: flip