# general
default_account: <PROJECT>
default_qos: normal

# working/log directories
chdir: ${env:HOME}/<WORK_DIR>
output: ${env:HOME}/<LOG_DIR>/%j.out

# environment setup
master_port: 55555
env_name: <ENV_NAME>

# LD_LIBRARY_PATH
ld_lib_path: /CONDA_ENV_PATH/.conda/envs/<ENV_NAME>/lib
